### ISSUE TITLE
[release_1.3] Improve current auth system

### ISSUE THREAD

**Issue by RonaldReagan** [assaultcube/AC#263]
The scope for the current auth is very limited. Additionally current implementation may be confusing to players. Some notes on it's current behavior: 
 - No auth interactions with MS (unlike sauer). It appears the mechanism is written in the MS, however it is unimplemented in the client.
 - Only used for client tracking (servervita.cfg)
   - Many stats/flags values aren't fully implemented
   - Many other vita values don't appear to be fully implemented (public/private comments, clans, 
 - Not hooked up to admin or user password mechanisms (there is a TODO to implement this)
 - If server uses the masterserver, or has the mandatory_auth flag enabled it will require auth on connect. So by default auth is required to connect to pubs.
 - Demos are signed by it?
 - Maps can have artist signature stored with them

Proposed changes:

- Use it as a replacement for server passwords & admin passwords (but do not eliminate those passwords as a possibility)
- Expose servervita stats to server admins ingame
- Generate a key automatically at client start.
- Change menus around to include more descriptive text
- Fully implement or eliminate the vita stats
- Better out of game documentation

**Comment by drian0** [comment]
Sounds good to me..

**Comment by RonaldReagan** [comment]
Added in the ability to use it for admin auth, whitelisting, and banning. I didn't add a way around the server password. I want to do more investigation about why server passwords are used before doing that.

Also removed vitastats that would require implementing new features. Thus far there is no way to mute players, prevent them from voting, or have a special map upload role. I have removed the vita stat values for those. If we want to implement those features we can do that at a later time.

I have implemented stat tracking for the game stats. The main philosophy here is to split out good vs bad stats instead of summing them up like we do for the scoreboard. This means that good kills & team kills are tracked independently, same with damage. To get total damage done you will want to do damage + friendly fire damage.

**Comment by RonaldReagan** [comment]
New proposed authentication flow:

- Default key is generated. This uses a standard pass, no pass (if possible), or a pass unique to the computer (computer mac or username?)
- Auth menu is reworked as auth operations menu. This menu can:
  - Show pub key (maybe even copy it to clipboard)
  - Set password
  - Remove saved password
  - Reset key entirely (do we even need this?)

I'm uneasy about setting a default key and leaving it relatively unprotected. However since most users won't actually use it for auth I think it is likely fine. Server owners when setting up admin can mandate their admins set a password (although enforcing it may be difficult).

**Comment by drian0** [comment]
The original code that I found in the experiemental/next branch required you to play a 10 minutes bot match in order to increase the security of the generated key. I did not consider this to be user friendly and removed that altogether. 

I agree that the current state is still not sufficiently good in terms of UX. My opinion is that we can prioritize convenience and user experience over security and so your suggestions makes sense to me. I would go with computer hardware information such as MAC address.

**Comment by RonaldReagan** [comment]
Sounds good, I'll pursue that.

Found another bug where key loading is slow enough to have not completed by the time a server is entered. In practice I'm not sure how quickly people enter servers but it may be worth either: (1) Reducing the iterations and/or (2) Adding a wait before making connections until the key finishes loading.

**Comment by RonaldReagan** [comment]
Added code to generate key at start. Instead of auto-generating keys, I added the auth setup menu to the new-game start dialog. If they generate a key without a password it will not default to something like the mac address. Only being able to develop on MacOS makes me uncomfortable with developing the crossplatform code and adequately testing it. One question I was unsure of is if we could reliably get the same adapter every time when attempting to get a MAC address.

Here are the new menus I added
<img width="806" alt="Screen Shot 2021-05-21 at 15 37 25" src="https://user-images.githubusercontent.com/1666762/119201022-4e114400-ba4b-11eb-9f49-dec29869248d.png">

<img width="886" alt="Screen Shot 2021-05-21 at 15 37 44" src="https://user-images.githubusercontent.com/1666762/119200943-30dc7580-ba4b-11eb-9d55-e799029561e8.png">

**Comment by BrutalSystem** [comment]
@RonaldReagan if the player has admin:1 set on servevita he should ignore the password requirement if the server has his private or match stage.

**Comment by RonaldReagan** [comment]
@BrutalSystem I believe you can connect, but the server browser doesn't reflect that. That is because it would require significant changes to the serverinfo protocol

**Comment by BrutalSystem** [comment]
@RonaldReagan when password is created the first time, password always appears while typing, password must be hidden.

enter password menu or any other menu where you enter password it should be mentioned that holding CTRL will show password.

**Comment by philocalyst** [comment]
All good here?
