### ISSUE TITLE
Assault cube crashing at start.

### ISSUE THREAD

**Issue by cartiace0d** [assaultcube/AC#465]
Assault Cube 1.2.0.2 crashing when I try to open it. It shows the loading screen then it crashes. PS: I've tried all other versions too and its the same.
Win32 Exception: 0xc0000005 [0x2367d0] 
This is the error that shows.
I've tried turning off DEP, changed the values in the .bat file to lower the resolution, installed .net and direct x even did a fresh windows installation but nothing seems to work. 
Will appreciate any help thanks.

**Comment by rpaugusto-eu** [comment]
My current installation also started giving out this error a few days ago. I belive it might have been some Windows updated that caused this: Included is a screenshot of the error and the folder the error refers to.
<img width="740" alt="AC_error1" src="https://user-images.githubusercontent.com/51327833/208313663-350340fc-6ad1-44f7-a3b6-d3f2adb4df02.PNG">

**Comment by rpaugusto-eu** [comment]
My current installation also started giving out this error a few days ago. I belive it might have been some Windows updated that caused this: Included is a screenshot of the error and the folder the error refers to.

Already tried to reinstall, same error occurs. Sometimes it loads the game, it crashes joining a server or I can join a server and crashes leaving the server... all random events.

<img width="740" alt="AC_error1" src="https://user-images.githubusercontent.com/51327833/208313663-350340fc-6ad1-44f7-a3b6-d3f2adb4df02.PNG">

**Comment by Macintoshin** [comment]
Solution? -
I found if i set the resolution at 800 x 600 before launching it fixes this issue, but the game does not switch to 800 x 600 it stays at the default monitor resolution. Idk if this works with other setups but this works for me

**Comment by HercFila** [comment]
Same issue on my end. I have Windows 11 as my main OS and seems like it is a problem with latest windows updates that cause this error. Tried installing latest version of the AC where the error is a bit different, sometimes it says it si missing a jpg file from for ladder top or bottom which I initially fixed with replacing all model textures with the previous version of AC. After fixing that problem the issue just loops back to Read Access Violation. Tried installing different version as different users and adding different permissions on all of these versions of AC... still didn't resolve the problem. What I found interesting is that rarely it would let me play the game (singplayer) mode also didn't matter but on certain maps I would get read access violation and on others I would play normally which leads me to believe that the jpg's are causing a problems. In the end its a weird rabbit hole of errors that I coulnd't figure out :)

**Comment by cartiace0d** [comment]
I fixed the problem. It seems it was a problem with the recent Amd drivers update. I rollbacked to old version and the issue resolved.

**Comment by HercFila** [comment]
> I fixed the problem. It seems it was a problem with the recent Amd drivers update. I rollbacked to old version and the issue resolved.

Interesting, which version of amd driver are you currently running on?

**Comment by adeliktas** [comment]
read https://github.com/assaultcube/AC/issues/308

**Comment by rpaugusto-eu** [comment]
Previous working AMD driver for AssaultCube is Adrenalin 22.5.1 but this causes problems in WarThunder, GPU driver crashes.

Just installed latest Adrenalin 23.2.1, released yesterday 2023/02/14, and problem still occurs in AssaultCube.

**Comment by HercFila** [comment]
I managed to fix the issue on my side by also installing the 22.5.1 version of AMD Drivers. Although it didn't work for me from the beginning because I had to do a clean install of drivers, meaning I had to use the AMD's Cleanup Utility to uninstall everything as well as drivers and then when I installed the 22.5.1 version everything worked normally (didn't test compatiblity with other games but I would assume the drivers are super outdated for newer games.).

Also one more issue I had when the older drivers were successfully installed was that my Windows 11 automatically forced to updates to AMD drivers to fix this I had to disable the Windows updates for any kind of drivers in Group Policy Editor, so every driver update you will have to do manually.

**Comment by ac-jamz** [comment]
For anyone suffering from this creash and using AMD drivers later than 22.6.1, please try installing the 64 bit client:
https://github.com/assaultcube/AC/archive/refs/heads/win-x64.zip
If you don't want to mess with your existing installation, you can simply copy the bin_win64 folder and assaultcube64.bat from the zip into your AC install folder (the same place you currently have bin_win32, probably c:\program files (x86)\AssaultCube 1.3.0.2).

**Comment by Macintoshin** [comment]
Thanks this worked 👍

**Comment by entr-py** [comment]
> For anyone suffering from this crash and using AMD drivers later than 22.6.1, please try installing the 64 bit client: https://github.com/assaultcube/AC/archive/refs/heads/win-x64.zip If you don't want to mess with your existing installation, you can simply copy the bin_win64 folder and assaultcube64.bat from the zip into your AC install folder (the same place you currently have bin_win32, probably c:\program files (x86)\AssaultCube 1.3.0.2).

This seems to only work sporadically for me, sometimes the client launches and is fine, but other times it launches and my memory usage peaks out (task manager shows AC using 16gb of memory?!) causing my computer to freeze before the client inevitably crashes. Sometimes even when it seems to be working fine, launching into random maps will then break it again. Not sure if this is still a widespread issue for AMD users still but worth noting I guess.
